### ISSUE TITLE
Great job at the presentation tonight! Taking a look at converting to swift 3.

### ISSUE THREAD

**Issue by thexande** [lostatseajoshua/custom-uiviewcontroller-transtions#1]
Do you plan on converting this syntax to swift 3 at some point?

**Comment by lostatseajoshua** [comment]
Thanks for coming! and yes I do plan on converting. I will have the implementation in swift 2.2, obj-c and swift 3. I am working on obj-c first before Swift 3. I will keep them projects separated in folders in the repo.
